version: '3'

services:
  db:
    image: mysql:5.7.22
    environment:
      MYSQL_ALLOW_EMPTY_PASSWORD: "yes"
    ports:
      - "4306:3306"
    volumes:
      - db-data:/var/lib/mysql
      - ./insides-api/mysqlconf:/etc/mysql/conf.d
  api:
    build: railsgym-api
    command: bash -c "rm -f tmp/pids/server.pid && bundle exec rails s -p 8080 -b '0.0.0.0'"
    volumes:
      - ./railsgym-api:/railsgym-api
      - bundle:/bundle
    ports:
      - "8080:8080"
    links:
      - db
    tty: true
    stdin_open: true
  web:
    build: railsgym
    tty: true
    command: sh -c "npm run dev"
    volumes:
      - ./railsgym:/railsgym
    ports:
      - "3000:3000"
    environment:
      - HOST=0.0.0.0
      - API_URL=http://api:8080
      - API_URL_BROWSER=http://localhost:8080
    links:
      - api
volumes:
  db-data:
    driver: local
  bundle:
    driver: local
