query($id: ID!) {
  item(id: $id) {
    id,
    title,
    url,
    createdAt,
    user {
      id
      username
    }
    reviews {
      content
      createdAt
      user {
        id
        username
      }
    }
  }
}
