default: &default
  adapter: mysql2
  encoding: utf8mb4
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  username: root
  password:
  host: <%= ENV.fetch('DB_HOST', 'db') %>
  port: 3306
  timeout: 5000
  charset: utf8mb4
  collation: utf8mb4_unicode_ci

development:
  <<: *default
  database: railsgym_api_development

test:
  <<: *default
  database: railsgym_api_test

production:
  <<: *default
  database: railsgym_api_production
  username: railsgym_api
  password: <%= ENV['RAILSGYM_API_DATABASE_PASSWORD'] %>
